version: "3.7"

services:
  worker:
    image: elixir:1.7.4
    hostname: worker
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ..:/app
    networks:
      - elixir_network

  manager:
    image: elixir:1.7.4
    hostname: manager
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ..:/app
    networks:
      - elixir_network

networks:
  elixir_network:
    driver: overlay
