version: "3.7"

services:
  worker:
    image: elixir:1.7.4 # elixir:latest # elixir:1.9.1-alpine
    hostname: worker_{{.Task.Slot}}
    working_dir: /app
    volumes:
      - ../distributed_pipeline:/app
    command: iex --sname worker --cookie ${SECRET} -S mix
    deploy:
      replicas: ${WORKER_REPLICAS}

  manager:
    image: elixir:1.7.4 # elixir:latest # elixir:1.9.1-alpine
    hostname: manager
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ../distributed_pipeline:/app
    environment:
      - WORKER_REPLICAS=${WORKER_REPLICAS}
